/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type UserCustomerTransformer from '#transformers/user_customer_transformer'
import type UserEstablishmentTransformer from '#transformers/user_establishment_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type UserCustomer = InferData<UserCustomerTransformer>
  export namespace UserCustomer {
    export type Variants = InferVariants<UserCustomerTransformer>
  }
  export type UserEstablishment = InferData<UserEstablishmentTransformer>
  export namespace UserEstablishment {
    export type Variants = InferVariants<UserEstablishmentTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
